// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqoiONo6BGD1B3KKscTMeMGENmarg37hk',
    appId: '1:642294786651:web:2ea17ef97fa7f56b4aad7e',
    messagingSenderId: '642294786651',
    projectId: 'ecomarecapp',
    authDomain: 'ecomarecapp.firebaseapp.com',
    storageBucket: 'ecomarecapp.appspot.com',
    measurementId: 'G-K98RT1WJPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwGI9KLu8wr-Hqmmi5HikMV3ToFLIpVtU',
    appId: '1:642294786651:android:e9777ccdc8ea43de4aad7e',
    messagingSenderId: '642294786651',
    projectId: 'ecomarecapp',
    storageBucket: 'ecomarecapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl2mqM7hIjKRqx0dwLlA5sXcP6mnoIqdE',
    appId: '1:642294786651:ios:fe1775c59148b9864aad7e',
    messagingSenderId: '642294786651',
    projectId: 'ecomarecapp',
    storageBucket: 'ecomarecapp.appspot.com',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl2mqM7hIjKRqx0dwLlA5sXcP6mnoIqdE',
    appId: '1:642294786651:ios:fe1775c59148b9864aad7e',
    messagingSenderId: '642294786651',
    projectId: 'ecomarecapp',
    storageBucket: 'ecomarecapp.appspot.com',
    iosBundleId: 'com.example.flowerApp',
  );
}
